<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

<?php echo $this->getChildHtml('after_body_start') ?>

<div id="container">

    <?php echo $this->getChildHtml('global_notices') ?>

    <?php echo $this->getChildHtml('header') ?>

    <div id="page">

	    <div class="l-two-col l-two-col-right l-wrap">
	            
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            
            <div class="l-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
            
            <div class="l-sidebar">
            	<?php echo $this->getChildHtml('right') ?>
            </div>
	        
	    </div>

    </div>

    <?php echo $this->getChildHtml('footer') ?>
    
    <?php echo $this->getChildHtml('before_body_end') ?>
        
</div>


<?php echo $this->getAbsoluteFooter(); ?>

</body>

</html>